# Your Solution
version: '3'
services:

  book-catalog:
    image: book-catalog
    build: 
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book-catalog
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - DATABASE_URL=postgresql://part3sit722_user:8LnpCURz8S4KqSXKjgPGDzBlm7zUiOPi@dpg-creq8tggph6c73eukqg0-a.oregon-postgres.render.com/part3sit722
    restart: "no"

  inventory-management:
    image: inventory-management
    build: 
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory-management
    ports:
     - "8082:8082"
    environment:
      - PORT=8082
      - DATABASE_URL=postgresql://part3sit722_user:8LnpCURz8S4KqSXKjgPGDzBlm7zUiOPi@dpg-creq8tggph6c73eukqg0-a.oregon-postgres.render.com/part3sit722
    restart: "no"
