# Your Solution
version: '3'
services:

  book-catalog:
    image: book-catalog
    build: 
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book-catalog
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - DATABASE_URL=postgresql://week7part3_user:XMZ2IBwcIAchVJiJT7IO6L22KsVSKcfO@dpg-creo8o0gph6c73eu1g5g-a.oregon-postgres.render.com/week7part3
    restart: "no"

  inventory-management:
    image: inventory-management
    build: 
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory-management
    ports:
     - "8082:8082"
    environment:
      - PORT=8082
      - DATABASE_URL=postgresql://week7part3_user:XMZ2IBwcIAchVJiJT7IO6L22KsVSKcfO@dpg-creo8o0gph6c73eu1g5g-a.oregon-postgres.render.com/week7part3
    restart: "no"
