# Your Solution
# Your Solution
# version: '3'
services:

  book-catalog:
    image: book-catalog
    build: 
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book-catalog
    ports:
      - "8000:8000"
    environment:
      # - PORT=8081
      - DATABASE_URL=postgresql://db722part3_user:65drNij74pm5pGOMP8g3MVOUZhGxe290@dpg-crio2u68ii6s73f716pg-a.oregon-postgres.render.com/db722part3
    restart: "no"

  inventory-management:
    image: inventory-management
    build: 
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory-management
    ports:
     - "8001:8001"
    environment:
      # - PORT=8082
      - DATABASE_URL=postgresql://db722part3_user:65drNij74pm5pGOMP8g3MVOUZhGxe290@dpg-crio2u68ii6s73f716pg-a.oregon-postgres.render.com/db722part3
    restart: "no"
