# Your Solution
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers:
      - name: book-catalog
        image: part3sit722.azurecr.io/book-catalog:latest
        imagePullPolicy: Always
        env:
        - name: PORT
          value: "8081"
        - name: DATABASE_URL
          value: "postgresql://part3sit722_user:8LnpCURz8S4KqSXKjgPGDzBlm7zUiOPi@dpg-creq8tggph6c73eukqg0-a.oregon-postgres.render.com/part3sit722"
---
apiVersion: v1
kind: Service
metadata:
  name: book-catalog
spec:
  selector:
    app: book-catalog
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      containers:
      - name: inventory-management
        image: part3sit722.azurecr.io/inventory-management:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
        env:
        - name: PORT
          value: "8082"
        - name: DATABASE_URL
          value: "postgresql://part3sit722_user:8LnpCURz8S4KqSXKjgPGDzBlm7zUiOPi@dpg-creq8tggph6c73eukqg0-a.oregon-postgres.render.com/part3sit722"
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-management
spec:
  selector:
    app: inventory-management
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8082
